name: Deployment to IIS on Azure VM

on:
    push:
        branches:
        - master

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout Code
              uses: actions/checkout@v2

            - name: Set up .NET Core
              uses: actions/setup-dotnet@v2
              with:
                dotnet-version: '8.0.x'

            - name: Restore Dependencies, download and install required NuGet packages
              run: dotnet restore MHRBuildTool/MHRBuildTool.sln

            - name: Build the project and compile application in 'Release' configuration
              run: dotnet build MHRBuildTool/MHRBuildTool.sln --configuration Release --no-restore

            - name: Publish the project
              run: dotnet publish MHRBuildTool/MHRBuildTool.sln -c Release -o publish

            - name: Ensure target directory exists on Azure VM
              run: |
                sshpass -p "${{ secrets.VM_PASSWORD }}" ssh -o StrictHostKeyChecking=no ${{ secrets.VM_USERNAME }}@${{ secrets.VM_IP }} "powershell -Command \"if (!(Test-Path 'C:\\Web\\MHRBuildTool')) { New-Item -Path 'C:\\Web\\MHRBuildTool' -ItemType Directory -Force } else { Remove-Item -Recurse -Force 'C:\\Web\\MHRBuildTool\\*' }\""

            - name: Clean target directory on Azure VM
              run: |
                sshpass -p "${{ secrets.VM_PASSWORD }}" ssh -o StrictHostKeyChecking=no ${{ secrets.VM_USERNAME }}@${{ secrets.VM_IP }} "powershell -Command \"Remove-Item -Recurse -Force 'C:\\Web\\MHRBuildTool\\*'\""
              
            - name: Copy files to Azure VM. Including the published project as well as the PowerShell script
              run: |
                sshpass -p "${{ secrets.VM_PASSWORD }}" scp -v -o ConnectTimeout=60 -o StrictHostKeyChecking=no -r ./publish/* ${{ secrets.VM_USERNAME }}@${{ secrets.VM_IP }}:"C:/Web/MHRBuildTool/"
                sshpass -p "${{ secrets.VM_PASSWORD }}" scp -v -o ConnectTimeout=60 -o StrictHostKeyChecking=no .github/workflows/deploy-to-iis.ps1 ${{ secrets.VM_USERNAME }}@${{ secrets.VM_IP }}:"C:/Web/deploy-to-iis.ps1"
           
            - name: Run deployment script on Azure VM
              run: |
                  sshpass -p "${{ secrets.VM_PASSWORD }}" ssh -o StrictHostKeyChecking=no ${{ secrets.VM_USERNAME }}@${{ secrets.VM_IP }} powershell.exe -File "C:/Web/deploy-to-iis.ps1" -_siteName "MHRBuildTool" -_sitePath "C:\inetpub\wwwroot\MHRBuildTool" -_sourcePath "C:Web/MHRBuildTool" -_port 5082

        env:
            VM_IP: ${{secrets.VM_IP}}
            VM_USERNAME: ${{secrets.VM_USERNAME}}
            VM_PASSWORD: ${{secrets.VM_PASSWORD}}


            
